FROM errornoyname/python3.13-uv:1.0
LABEL Autor='Null_Name'
COPY ./src/app/ /root/1c-wastepaper/
WORKDIR /root/1c-wastepaper/
EXPOSE 25565
RUN ["/root/.local/bin/uv", "sync"]
CMD ["/root/.local/bin/uv", "run", "main.py"]
