FROM node:22
LABEL Autor='Null_Name'
ADD ./src/app/frontend/ /root/advertising_management/
WORKDIR /root/advertising_management/src
RUN apt update
RUN cd /root/advertising_management/ && npm install 
EXPOSE 5173
CMD ["npm", "run", "dev"]